name: compile test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: pacman
        run: |
          pacman -Sy --noconfirm \
            git \
            sfml \
            base-devel \
            clang
      - name: checkout
        uses: actions/checkout@v4
      - name: make
        run: make
